// Initialize sample annotations for development
// import { createAnnotation } from "~/lib/annotationService"
import { annotationService } from "~/lib/annotationService"

export async function initializeSampleAnnotations() {
  const sampleAnnotations = [
    {
      video_id: "1",
      timestamp: "2024-01-01T10:00:00Z",
      time: 0,
      x: 100,
      y: 200,
      xPercent: 10,
      yPercent: 20,
      category: "phases" as const,
      phaseName: "Preparation",
      endTime: 60,
      duration: 60,
    },
    {
      video_id: "1",
      timestamp: "2024-01-01T10:01:00Z",
      time: 60,
      x: 120,
      y: 220,
      xPercent: 20,
      yPercent: 30,
      category: "phases" as const,
      phaseName: "Incision",
      endTime: 120,
      duration: 60,
    },
    {
      video_id: "1",
      timestamp: "2024-01-01T10:02:00Z",
      time: 120,
      x: 140,
      y: 240,
      xPercent: 30,
      yPercent: 40,
      category: "events" as const,
      eventName: "Bleeding Started",
    },
    {
      video_id: "1",
      timestamp: "2024-01-01T10:03:00Z",
      time: 180,
      x: 160,
      y: 260,
      xPercent: 40,
      yPercent: 50,
      category: "bleeds" as const,
      interventionTime: 200,
      severity: "moderate" as const,
    },
    {
      video_id: "1",
      timestamp: "2024-01-01T10:04:00Z",
      time: 240,
      x: 180,
      y: 280,
      xPercent: 50,
      yPercent: 60,
      category: "instrumentation" as const,
      instrumentName: "Scalpel",
      position: "Center" as const,
      endTime: 300,
      duration: 60,
    },
    {
      video_id: "1",
      timestamp: "2024-01-01T10:05:00Z",
      time: 300,
      x: 200,
      y: 300,
      xPercent: 60,
      yPercent: 70,
      category: "anomaly" as const,
      description: "Unexpected tissue response",
      note: "Monitor closely",
    },
    {
      video_id: "1",
      timestamp: "2024-01-01T10:06:00Z",
      time: 360,
      x: 220,
      y: 320,
      xPercent: 70,
      yPercent: 80,
      category: "phases" as const,
      phaseName: "Dissection",
      endTime: 420,
      duration: 60,
    },
    {
      video_id: "1",
      timestamp: "2024-01-01T10:07:00Z",
      time: 420,
      x: 240,
      y: 340,
      xPercent: 80,
      yPercent: 90,
      category: "events" as const,
      eventName: "Suturing Started",
    },
    {
      video_id: "1",
      timestamp: "2024-01-01T10:08:00Z",
      time: 480,
      x: 260,
      y: 360,
      xPercent: 90,
      yPercent: 95,
      category: "instrumentation" as const,
      instrumentName: "Needle Holder",
      position: "Left" as const,
      endTime: 540,
      duration: 60,
    },
    {
      video_id: "1",
      timestamp: "2024-01-01T10:09:00Z",
      time: 540,
      x: 280,
      y: 380,
      xPercent: 95,
      yPercent: 99,
      category: "phases" as const,
      phaseName: "Closure",
      endTime: 600,
      duration: 60,
    },
  ]

  for (const annotation of sampleAnnotations) {
    try {
      await annotationService.createAnnotation(annotation)
    } catch (error) {
      console.log("Annotation already exists or error:", error)
    }
  }
}